sudo: required
services:
  - docker
before_install:
  - docker build -t kunwarluthera/multi-docker -f ./client/Dockerfile.dev ./client
script:
  - docker run kunwarluthera/multi-docker npm test -- --coverage 
after_success:
  - docker build -t kunwarluthera/multi-client ./client
  - docker build -t kunwarluthera/multi-nginx ./nginx
  - docker build -t kunwarluthera/multi-server ./server
  - docker build -t kunwarluthera/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kunwarluthera/multi-client
  - docker push kunwarluthera/multi-nginx
  - docker push kunwarluthera/multi-server
  - docker push kunwarluthera/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-738585724471
  bucket_path: docker-multi
  on:
    branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"